edgee-cloud/docs

api-reference/openapi.json
To maximize Edgee’s efficiency, it is best to ensure that computed content is not cacheable by browsers or shared caches.
However, upstream servers may add cache-control directives that are difficult to modify or remove.
In such cases, you can override the cache-control directive with a no-store policy to prevent content from being cached.
https://github.com/edgee-cloud/edgee/issues/74
=> feat: option to enforce no-store cache policy

open-source/overview.mdx
Add install script usage in the `open-source` section.
- edgee-cloud/edgee#86
=> doc(open-source): Add documentation for using the install script

_snippets/data-collection-catalog.mdx, getting-started.mdx, getting-started/domains.mdx, getting-started/js-sdk.mdx, getting-started/project-settings.mdx, getting-started/react-sdk.mdx, getting-started/routing.mdx, getting-started/sdk.mdx, introduction.mdx, introduction/architecture.mdx, introduction/faq.mdx, introduction/network-map.mdx, mint.json, package-lock.json, package.json, services/ab-testing/catalog.mdx, services/ab-testing/overview.mdx, services/data-collection/catalog.mdx, services/data-collection/context-payload.mdx, services/data-collection/data-loss-estimation.mdx, services/data-collection/identify-event.mdx, services/data-collection/overview.mdx, services/data-collection/page-event.mdx, services/data-collection/privacy.mdx, services/data-collection/track-event.mdx, services/overview.mdx, services/security/access-control.mdx, services/security/catalog.mdx, services/security/https-enforcement.mdx, services/security/overview.mdx
- Overall copy review
- added a couple of missing pages (broken links)
- improved nav menu and icons
=> feat: overall copy review

getting-started/sdk.mdx, package-lock.json, package.json
Just a minor `<Note>` to clarify why the SDK is automatically inlined.
=> Doc: clarify that the SDK is inlined automatically

api-reference/data-collection-events/endpoints.mdx, api-reference/data-collection-events/incoming-object.mdx, api-reference/data-collection-events/list-incoming.mdx, api-reference/data-collection-events/list-outgoing.mdx, api-reference/data-collection-events/outgoing-object.mdx, api-reference/openapi.json, mint.json, package-lock.json, package.json
New endpoints about incoming and outgoing data collection events
No issue
=> feat: add two new endpoints

components/data-collection/amplitude.mdx, components/data-collection/piano-analytics.mdx, components/data-collection/segment.mdx, package-lock.json, package.json
- Add link to new GitHub project for Piano Analytics
- Add useful links and better direction to find your API keys
=> New piano analytics component

getting-started.mdx, getting-started/react-sdk.mdx, mint.json, package-lock.json, package.json, services/data-collection/data-layer.mdx, services/data-collection/overview.mdx, services/data-collection/page-event.mdx
A few improvements:
- remove waiting list mention
- enable theme (light/dark) for code snippets
- new advanced footer with website links
- restructure some code snippets
- add highlighted lines in code snippets (new Mintlify feature)
=> Docs improvements

api-reference/openapi.json, api-reference/proxy-settings/create.mdx, api-reference/proxy-settings/endpoints.mdx, api-reference/proxy-settings/list.mdx, api-reference/proxy-settings/update.mdx, package-lock.json, package.json
When Edgee is installed in a complex network routing, it could listen to a specific host which is not the same as the one used by the client.
In that case, edgee user must be able to specify a cookie_domain.
No related issue
=> feat: add cookie_domain

getting-started/js-sdk.mdx, getting-started/react-sdk.mdx, package-lock.json, package.json, services/data-collection/overview.mdx
Update docs to include client-side SDK in the `<head>` tag (instead of at the end of the `<body>` tag).
=> Edgee SDK in <head> tag

api-reference/openapi.json
remove type filtering from get /v1/organizations
=> remove type from org list api

components/data-collection/google-analytics.mdx, package-lock.json, package.json
Enhance GA4 component documentation with e-commerce specifications
No issue
=> feat: ga ecommerce event

package-lock.json, package.json, services/data-collection/user-event.mdx
New specification about the user event
No issue
=> feat: new user event spec

api-reference/data-collection/openapi.json
Following the last SDK fix, we need to fix the openAPI doc here as well
=> fix: wrong field

api-reference/openapi.json, mint.json, package-lock.json, package.json
Docs URL update, and some little stuffs
=> chore: doc url update

api-reference/openapi.json
Simplify the component settings
No issue
=> chore: improve component settings

package-lock.json, package.json
Bump Mintlify version to fix the dependabot alert: https://github.com/edgee-cloud/docs/security/dependabot/2 
[List related issues here](https://github.com/edgee-cloud/docs/security/dependabot/2)
=> chore: bump mintlify version

api-reference/counters/component_list.mdx, api-reference/counters/component_object.mdx, api-reference/counters/endpoints.mdx, api-reference/counters/list.mdx, api-reference/counters/object.mdx, api-reference/openapi.json, mint.json, package-lock.json, package.json
=> add counter api docs

api-reference/data-collection-events/endpoints.mdx, api-reference/data-collection-events/list-incoming.mdx, api-reference/data-collection-events/list-outgoing.mdx, api-reference/openapi.json
For a better understanding
- Change `/v1/projects/{id}/incoming_data_collection_events` by `/v1/projects/{id}/debug/data-collection/incoming`
- Change `/v1/projects/{id}/outgoing_data_collection_events/{event_id}` by `/v1/projects/{id}/debug/data-collection/outgoing/{event_id}`
No issue
=> feat: data collection debug events change

api-reference/openapi.json
Some `User` fields were not present from the OpenAPI file, along some metadata regarding "required" fields
=> Add missing OpenAPI doc

api-reference/openapi.json, package-lock.json, package.json
This PR reflects the changes made on the GET User Endpoint, returning a `roles` property that contains a map of `OrganizationID => UserRole`.
=> Update v1/user/id & v1/user/me Endpoints

api-reference/components/get-by-slug.mdx, api-reference/components/update-by-slug.mdx, api-reference/components/update.mdx, api-reference/openapi.json, components/data-collection/amplitude.mdx, components/data-collection/google-analytics.mdx, components/data-collection/meta-capi.mdx, components/data-collection/piano-analytics.mdx, components/data-collection/segment.mdx, mint.json, package-lock.json, package.json, services/data-collection/data-layer.mdx, services/data-collection/page-event.mdx, services/data-collection/track-event.mdx, services/data-collection/user-event.mdx
=> feat: new slugs

getting-started/react-sdk.mdx, package-lock.json, package.json
This PR introduces a documentation for our New REACT SDK hook `useEdgeeDataCollection`.
=> Add useEdgeeDataCollection React SDK Hook Documentation

api-reference/components/create.mdx, api-reference/components/delete.mdx, api-reference/components/version-create.mdx, api-reference/components/version-update.mdx, api-reference/openapi.json, docs.json
=> Component api

api-reference/openapi.json
add external_project_url when creating a new project
=> openapi: add external_project_url in projects

open-source/overview.mdx, services/registry/developer-guide.mdx
Just a quick fix to update the S3 repository name.
=> Update links to S3 repository

package-lock.json, package.json, services/registry/developer-guide.mdx
New features for CLI 0.8.3:
- `edgee self-update` (I've added a new sub-section for version updates)
- `edgee components new --name my-component --language rust` (quick update in the `new` section)
- automatic check on push (just a quick comment)
- `edgee components test [options] --make-http-request` and  `--curl` (I've added a new sub-sections about testing HTTP requests)
=> Document new CLI features

package-lock.json, package.json, services/registry/developer-guide.mdx
- add new `cargo binstall` instructions
- add new `icon-path` manifest field
- add warning and step-by-step instruction to update existing components to WIT 0.5.0
=> CLI release 0.8.6 and WIT breaking change

api-reference/openapi.json
Add Inject SDK field to the project
=> feat: add inject-sdk field

package-lock.json, package.json, services/registry/developer-guide.mdx
- added auto-completion section
=> Update registry docs for Edgee CLI v0.8.7

package-lock.json, package.json, services/registry/developer-guide.mdx, services/registry/faqs.mdx, services/registry/foundations.mdx, services/registry/overview.mdx
1. Remove all BETA referenecs
2. Overall copyediting pass
3. Add latest feature (login via env variable, credentials file location, login profiles, etc.)
4. Add a few website links here and there (pricing, etc.)
=> Update registry docs for the public launch

components/data-collection/posthog.mdx, docs.json, open-source/overview.mdx
=> feat: add posthog doc

services/data-collection/privacy.mdx
=> feat: cookieless

api-reference/openapi.json, package-lock.json, package.json
- remove requestBody from GET endpoints
- ad new reusable #/components/parameters/ $refs
=> Fix openapi get querystring

api-reference/openapi.json
Update openapi.json to reflect API changes (override cache)
=> feat: override cache

components/data-collection/google-analytics.mdx
=> feat: ga4 user event

components/data-collection/amazon-data-firehose.mdx, components/data-collection/amazon-kinesis.mdx, components/data-collection/amazon-s3.mdx, components/data-collection/clickhouse.mdx, docs.json, package-lock.json, package.json
New page for ClickHouse plus a couple of minor typos to fix.
Component PR is here: https://github.com/edgee-cloud/clickhouse-component/pull/1
=> Add new page for ClickHouse Component

components/data-collection/google-bigquery.mdx, docs.json, package-lock.json, package.json
=> bigquery compoentn docs

snippets/consent-management-catalog.mdx, snippets/data-collection-catalog.mdx, snippets/endpoint-catalog.mdx, snippets/identity-catalog.mdx, snippets/sdk-gateway-catalog.mdx
- fix a merge conflict
- add S3 URL prefix to avoid broken icons (for now)
This is a temporary solution, we need to find a way to use simple absolute URLs for Card icons (same as all the other docs images).
=> Components overview fix

package-lock.json, package.json, services/registry/developer-guide-edge-function.mdx
Document custom port and watch mode for edge function local testing.
=> Edge function updates

components/ab-testing/kameleoon.mdx, components/overview.mdx, docs.json, package-lock.json, package.json, snippets/ab-testing-catalog.mdx
- Add the "Stitching" category with the "A/B Testing subcategory"
- Add a documentation page for Kameleoon
- Resolves EDGEE-722
=> feat: add Stitching category and Kameleoon component page

package-lock.json, package.json, services/registry/developer-guide-data-collection.mdx, services/registry/developer-guide-edge-function.mdx, snippets/warning-cli-build-command.mdx
Only a couple of doc updates (both DC and EF).
Note: we need to release edgee@1.2.19 first :)
- https://linear.app/edgee/issue/EDGEE-628/stacktrace-documentation
=> Update CLI documentation: stacktrace debugging and auto-build on test

package-lock.json
=> vuln: fix axios

introduction/network-map.mdx, package-lock.json, package.json, services/registry/developer-guide.mdx, snippets/ab-testing-catalog.mdx, snippets/consent-management-catalog.mdx, snippets/data-collection-catalog.mdx, snippets/edge-function-catalog.mdx, snippets/endpoint-catalog.mdx, snippets/identity-catalog.mdx, snippets/sdk-gateway-catalog.mdx, snippets/security-catalog.mdx, style.css
The Mintlify team suggested using 
```mdx
<Card ... icon="/path/to/image.svg" />
```
instead of 
```mdx
<Card ... icon={<img src="..." alt="..." />} />
```
This seems to work, even if there are two minor issues:
1.  an annoying css bug that forces all icon background to be primary-bg (instead of transparent) -> I have added a custom css rule to override that.
2. in order to support light/dark variations for card icons, you'd need to define two `<Card>` elements inside `<div className="block dark:hidden">` and `<div className="hidden dark:block">`  (not super elegant, but still a better workaround than the current one).
=> <Card> Icon fix (WIP)

api-reference/openapi.json, package-lock.json, package.json
Add project `type` field in OpenAPI specs
=> feat: project types

api-reference/openapi.json
=> fix: project types
